name: dbnus
description: "Test des"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  # State Management
  equatable: 2.0.7
  flutter_bloc: ^9.1.0
  bloc: ^9.1.0

  # Network
  http: ^1.6.0
  socket_io_client: ^3.1.3
  connectivity_plus: ^7.0.0
  # network_info_plus: 6.1.3

  # Route Manager
  go_router: ^17.0.1
  app_links: ^7.0.0

  #Firebase
  firebase_core: ^4.3.0
  firebase_messaging: ^16.1.0
  firebase_analytics: ^12.1.0
  firebase_crashlytics: ^5.0.6
  firebase_performance: ^0.11.1+3

  # Utility Functions
  uuid: ^4.5.2
  intl: any
  xml2json: ^6.2.7
  encrypt: 5.0.3
  web: ^1.1.1
  permission_handler: ^12.0.1
  camera: ^0.11.3
  universal_html: ^2.3.0
  crypto: ^3.0.7

  # Features
  in_app_review: ^2.0.11
  share_plus: ^12.0.1
  open_file: 3.5.10
  flutter_local_notifications: ^19.0.0
  url_launcher: ^6.3.2
  back_button_interceptor: ^8.0.4
  flutter_localizations:
    sdk: flutter

  # Storage
  shared_preferences: ^2.5.2
  #  localstore: 1.3.5
  hive: 2.2.3
  path_provider: 2.1.5

  # Location
  geocoding: ^4.0.0
  geolocator: ^14.0.1

  # Device Information
  flutter_udid: ^4.1.1
  # custom_platform_device_id: 1.0.8
  device_info_plus: ^12.3.0
  universal_io: ^2.3.1
  package_info_plus: ^9.0.0

  # File Handling
  file_picker: ^10.3.8
  image_picker: ^1.2.1
  flutter_image_compress: 2.4.0

  # Ui & Animations
  shimmer: 3.0.0
  animated_text_kit: ^4.2.3
  pin_code_fields: 8.0.1
  syncfusion_flutter_charts: ^32.1.21
  flutter_spinkit: ^5.2.2
  flutter_svg: ^2.2.3
  flutter_staggered_grid_view: 0.7.0
  expandable_text: 2.3.0
  google_fonts: ^6.3.3
  flutter_widget_from_html_core: ^0.17.0
  # dyte_uikit: 0.7.0
  flutter_inappwebview: 6.1.5
  cupertino_icons: 1.0.8
  cached_network_image: 3.4.1
  flame: ^1.25.0
  flame_forge2d: ^0.19.2+2
  flame_svg: ^1.11.6

  # Payment
  # paytm_allinonesdk: 1.2.6
  razorpay_flutter: ^1.4.0
  flutter_razorpay_web: 0.0.3

  # Download
  # flutter_downloader: 1.11.6
  background_downloader: ^9.0.0

  #update:
  in_app_update: ^4.2.5
  new_version_plus: ^0.1.0

  # Media Players
  audioplayers: ^6.2.0
  flutter_volume_controller: ^1.3.4
  video_player: ^2.9.5
  flame_audio: ^2.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_flavorizr: ^2.3.0

flutter:

  uses-material-design: true

  generate: true

  assets:
    - assets/design/
    - assets/images/
    - assets/icon/
    - assets/store/
    - assets/sound/
    - assets/js/